// src/agent/personalizationLoop.js
// ═══════════════════════════════════════════════════════════
// LOCAL PERSONALIZATION  (Feature #4 — HONEST SCOPE)
//
// What this file actually does: collects your corrections
// (whenever you edit or reject an agent output) into a properly
// formatted, fine-tuning-ready dataset, entirely on your PC.
//
// What this file does NOT do: automatically retrain the model.
// Real LoRA fine-tuning needs a training loop, tokenizer matched
// to your exact base model, and meaningful compute time — that's
// a separate, deliberate action (a script you run when you have
// ~50+ good examples and a few free minutes of GPU time), not
// something that should happen silently in the background of an
// Electron app. Claiming otherwise would be describing a feature
// that doesn't actually exist.
//
// This gives you the REAL, useful part today: your corrections
// are never lost, they're stored in the exact JSONL format tools
// like Unsloth/Axolotl expect, and a one-command export is ready
// whenever you want to actually run a training pass.
// ═══════════════════════════════════════════════════════════

const fs   = require("fs");
const path = require("path");
const os   = require("os");

const CORRECTIONS_DIR = path.join(os.homedir(), ".vnus-agent", "corrections");
if (!fs.existsSync(CORRECTIONS_DIR)) fs.mkdirSync(CORRECTIONS_DIR, { recursive: true });

const CORRECTIONS_FILE = path.join(CORRECTIONS_DIR, "corrections.jsonl");
const EXPORT_DIR        = path.join(CORRECTIONS_DIR, "exports");
if (!fs.existsSync(EXPORT_DIR)) fs.mkdirSync(EXPORT_DIR, { recursive: true });

// ── Record a correction — call this whenever the user edits or
// explicitly rejects an agent's output ──────────────────────
function recordCorrection(originalPrompt, agentOutput, userCorrection, meta = {}) {
  const entry = {
    messages: [
      { role: "system", content: meta.systemPrompt || "You are Agentic Vnus." },
      { role: "user", content: originalPrompt },
      { role: "assistant", content: userCorrection }, // the CORRECTED version is what we train toward
    ],
    metadata: {
      originalOutput: agentOutput,
      agentId:        meta.agentId || "boss",
      recordedAt:     new Date().toISOString(),
    },
  };

  fs.appendFileSync(CORRECTIONS_FILE, JSON.stringify(entry) + "\n");
  return entry;
}

// ── How many corrections do we have, and is it worth exporting? ──
function getCorrectionStats() {
  if (!fs.existsSync(CORRECTIONS_FILE)) return { count: 0, readyToExport: false };

  const lines = fs.readFileSync(CORRECTIONS_FILE, "utf8").split("\n").filter(Boolean);
  const byAgent = {};
  lines.forEach(line => {
    try {
      const entry = JSON.parse(line);
      const agentId = entry.metadata?.agentId || "boss";
      byAgent[agentId] = (byAgent[agentId] || 0) + 1;
    } catch {}
  });

  return {
    count: lines.length,
    byAgent,
    // 50 is a commonly cited practical minimum for a LoRA pass to
    // show any real signal without overfitting on noise
    readyToExport: lines.length >= 50,
  };
}

// ── Export a training-ready JSONL file + a ready-to-run script ──
// The script is provided but NEVER auto-executed — training is
// always something the user explicitly chooses to run.
function exportForFineTuning(agentId = null) {
  if (!fs.existsSync(CORRECTIONS_FILE)) {
    return { success: false, error: "No corrections recorded yet" };
  }

  const lines = fs.readFileSync(CORRECTIONS_FILE, "utf8").split("\n").filter(Boolean);
  const filtered = agentId
    ? lines.filter(l => { try { return JSON.parse(l).metadata?.agentId === agentId; } catch { return false; } })
    : lines;

  if (filtered.length < 10) {
    return { success: false, error: `Only ${filtered.length} corrections available — need at least 10 for a meaningful export` };
  }

  const exportName = `finetune-${agentId || "all"}-${Date.now()}.jsonl`;
  const exportPath = path.join(EXPORT_DIR, exportName);
  fs.writeFileSync(exportPath, filtered.join("\n"));

  const scriptPath = path.join(EXPORT_DIR, "run-finetune.sh");
  fs.writeFileSync(scriptPath, `#!/bin/bash
# Generated by Agentic Vnus — local fine-tuning helper
# This does NOT run automatically. Review it, then run it yourself
# when you have a few minutes of local GPU time available.
#
# Requires: pip install unsloth (see https://github.com/unslothai/unsloth)
# Adjust --base-model to match whatever Ollama model you're running.

echo "Fine-tuning on: ${exportName}"
echo "Examples: ${filtered.length}"
echo ""
echo "This is a starting point, not a one-click black box — review"
echo "the base model name and hyperparameters below before running."
echo ""

python -m unsloth.finetune \\
  --base-model "unsloth/llama-3-8b" \\
  --dataset "${exportPath}" \\
  --output-dir "${path.join(EXPORT_DIR, "adapter-" + Date.now())}" \\
  --lora-r 16 \\
  --epochs 3 \\
  --learning-rate 2e-4
`);
  try { fs.chmodSync(scriptPath, 0o755); } catch {}

  return {
    success: true,
    exportPath,
    scriptPath,
    exampleCount: filtered.length,
    message: `${filtered.length} examples exported. Review ${scriptPath} before running it — nothing trains automatically.`,
  };
}

module.exports = {
  recordCorrection,
  getCorrectionStats,
  exportForFineTuning,
};